
// EXTERNAL OMDB API DATA

export const movies = [
      {
      id: 1,
      Title: "Zz: The Fast and the Furious",
      url: "assets/The Fast and the Furious.png",
      Year: "2001",
      originalPrice: 25.35,
      salePrice: 16.66,
      rating: 2.5,      
    },
    {
      id: 2,
      Title: "Bb: Fast & Furious 6",
      url: "assets/Fast & Furious 6.png",
      Year: "2013",
      originalPrice: 11.55,
      salePrice: 9.99,
      rating: 5,      
    },
    {
      id: 3,
      Title: "Qq: Fast Five",
      url: "assets/Fast Five.png",
      Year: "2011",
      originalPrice: 13.13,
      salePrice: 10.15,
      rating: 5,      
    },
    {
      id: 4,
      Title: "Mm: Fast & Furious",
      url: "assets/Fast & Furious.png",
      Year: "2009",
      originalPrice: 20.11,
      salePrice: 18.23,
      rating: 2,      
    },    
    {
      id: 5,
      Title: "Ll: 2 Fast 2 Furious",
      url: "assets/2 Fast 2 Furious.png",
      Year: "2003",
      originalPrice: 17.11,
      salePrice: 15.87,
      rating: 3.5,
      
    },    
    {
      id: 6,
      Title: "Gg: Fast X",
      url: "assets/Fast X.png",
      Year: "2023",
      originalPrice: 32.22,
      salePrice: 26.15,
      rating: 3,      
    },    
    {
      id: 1,
      Title: "Ss: The Fast and the Furious",
      url: "assets/The Fast and the Furious.png",
      Year: "2001",
      originalPrice: 42.35,
      salePrice: 25.66,
      rating: 5, 
      
    },
    {
      id: 2,
      Title: "Kk: Fast & Furious 6",
      url: "assets/Fast & Furious 6.png",
      Year: "2013",
      originalPrice: 60.55,
      salePrice: 55.55,
      rating: 3.5,      
    },
    {
      id: 3,
      Title: "Tt: Fast Five",
      url: "assets/Fast Five.png",
      Year: "2011",
      originalPrice: 41.13,
      salePrice: 37.15,
      rating: 1.5,      
    },
    {
      id: 4,
      Title: "Pp: Fast & Furious",
      url: "assets/Fast & Furious.png",      
      Year: "2009",
      originalPrice: 70.11,
      salePrice: 65.23,
      rating: 4.5,      
    },    
    {
      id: 6,
      Title: "Ww: 2 Fast 2 Furious",
      url: "assets/2 Fast 2 Furious.png",
      Year: "2003",
      originalPrice: 80.11,
      salePrice: 76.34,
      rating: 1.5,      
    },    
    {
      id: 9,
      Title: "Yy: Fast X",
      url: "assets/Fast X.png",
      Year: "2023",
      originalPrice: 98.22,
      salePrice: 81.15,
      rating: 1,      
    },    
  ];